export const job_options=[{ value: 'frontend', label: 'FrontEnd' },
    { value: 'backend', label: 'BackEnd' },
    { value: 'android', label: 'Android' },
    { value: 'ios', label: 'IOS' },
    { value: 'tech lead', label: 'Tech Lead' }]
export const location_options=[{ value: 'remote', label: 'Remote' },
    { value: 'chennai', label: 'Chennai' },
    { value: 'bangalore', label: 'Bangalore' },
    { value: 'mumbai', label: 'Mumbai' },
    { value: 'delhi ncr', label: 'Delhi' }]
export const numberOfEmployees =[{ value: 'remote', label: '1-10' },
{ value: '11-20', label: '11-20' },
{ value: '21-50', label: '21-50' },
{ value: '51-100', label: '51-100' },
{ value: '101-200', label: '101-200' },
{ value: '201-500', label: '201-500' },
{ value: '500+', label: '500+' }]
export const experience=[{ value: 1, label: '1' },
{ value: 2, label: '2' },
{ value: 3, label: '3' },
{ value: 4, label: '4' },
{ value: 5, label: '5' },
{ value: 6, label: '6' },
{ value: 7, label: '7' },
{ value: 8, label: '8' },
{ value: 9, label: '9' },
{ value: 10, label: '10' },]
export const minBaseSalary=[{ value: 1, label: '1k' },
{ value: 5, label: '5k' },
{ value: 10, label: '10k' },
{ value: 20, label: '20k' },
{ value: 30, label: '30k' },
{ value: 40, label: '40k' },
{ value: 50, label: '50k' }]

